[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["python -m venv .venv", ". .venv/bin/activate", "pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "bash start.sh"
